MvcExamenAWSAlvaroMoyaHerraiz/Models/Apuesta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MvcExamenAWSAlvaroMoyaHerraiz.Models
{
    [Table("APUESTAS")]
    public class Apuesta
    {
        [Key]
        [Column("IDAPUESTA")]
        public int IdApuesta { get; set; }

        [Column("USUARIO")]
        public string Usuario { get; set; }

        [Column("IDEQUIPOLOCAL")]
        public int IdLocal { get; set; }

        [Column("IDEQUIPOVISITANTE")]
        public int IdVisitante { get; set; }

        [Column("GOLESEQUIPOLOCAL")]
        public int GolesLocal { get; set; }

        [Column("GOLESEQUIPOVISITANTE")]
        public int GolesVisitante { get; set; }
    }
}

MvcExamenAWSAlvaroMoyaHerraiz/Models/Equipo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MvcExamenAWSAlvaroMoyaHerraiz.Models
{
    [Table("EQUIPOS")]
    public class Equipo
    {
        [Key]
        [Column("IDEQUIPO")]
        public int IdEquipo { get; set; }

        [Column("NOMBRE")]
        public string Nombre { get; set; }

        [Column("IMAGEN")]
        public string Imagen { get; set; }

        [Column("CHAMPIONS")]
        public int Champions { get; set; }

        [Column("WEB")]
        public string Web { get; set; }

        [Column("DESCRIPCION")]
        public string Descripcion { get; set; }
    }
}

MvcExamenAWSAlvaroMoyaHerraiz/Models/ErrorViewModel.cs
using System;

namespace MvcExamenAWSAlvaroMoyaHerraiz.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcExamenAWSAlvaroMoyaHerraiz/Models/Jugador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MvcExamenAWSAlvaroMoyaHerraiz.Models
{
    [Table("JUGADORES")]
    public class Jugador
    {
        [Key]
        [Column("IDJUGADOR")]
        public int IdJugador { get; set; }

        [Column("NOMBRE")]
        public string Nombre { get; set; }

        [Column("POSICION")]
        public string Posicion { get; set; }

        [Column("IMAGEN")]
        public string Imagen { get; set; }

        [Column("IDEQUIPO")]
        public int IdEquipo { get; set; }
    }
}

MvcExamenAWSAlvaroMoyaHerraiz/Controllers/ApuestasController.cs
using Microsoft.AspNetCore.Mvc;
using MvcExamenAWSAlvaroMoyaHerraiz.Models;
using MvcExamenAWSAlvaroMoyaHerraiz.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcExamenAWSAlvaroMoyaHerraiz.Controllers
{
    public class ApuestasController : Controller
    {

        private RepositoryChampions repo;

        public ApuestasController(RepositoryChampions repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Equipo> equipos = this.repo.GetEquipos();
            ViewData["EQUIPOS"] = equipos;
            return View(this.repo.GetApuestas());
        }

        [HttpPost]
        public IActionResult Index(string usuario,int idlocal,int idvisitante,int gollocal,int golvisitante)
        {
            Apuesta apuesta = new Apuesta();
            apuesta.IdApuesta = this.repo.GetMaxIdApuesta();
            apuesta.Usuario = usuario;
            apuesta.IdLocal = idlocal;
            apuesta.IdVisitante = idvisitante;
            apuesta.GolesLocal = gollocal;
            apuesta.GolesVisitante = golvisitante;
            this.repo.CrearApuesta(apuesta);
            return RedirectToAction("Index");
        }
    }
}

MvcExamenAWSAlvaroMoyaHerraiz/Controllers/EquiposController.cs
using Microsoft.AspNetCore.Mvc;
using MvcExamenAWSAlvaroMoyaHerraiz.Models;
using MvcExamenAWSAlvaroMoyaHerraiz.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcExamenAWSAlvaroMoyaHerraiz.Controllers
{
    public class EquiposController : Controller
    {
        private RepositoryChampions repo;

        public EquiposController(RepositoryChampions repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Equipo> equipos = this.repo.GetEquipos();
            return View(equipos);
        }
    }
}

MvcExamenAWSAlvaroMoyaHerraiz/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcExamenAWSAlvaroMoyaHerraiz.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcExamenAWSAlvaroMoyaHerraiz.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcExamenAWSAlvaroMoyaHerraiz/Controllers/JugadoresController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcExamenAWSAlvaroMoyaHerraiz.Models;
using MvcExamenAWSAlvaroMoyaHerraiz.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MvcExamenAWSAlvaroMoyaHerraiz.Controllers
{
    public class JugadoresController : Controller
    {
        private RepositoryChampions repo;

        public JugadoresController(RepositoryChampions repo)
        {
            this.repo = repo;
        }

        public IActionResult Index(int idequipo)
        {
            List<Jugador> jugadores = this.repo.GetJugadores(idequipo) ;
            ViewData["ID"] = idequipo;
            return View(jugadores);
        }

        public IActionResult Create(int idequipo)
        {
            Equipo equipo = this.repo.FindEquipo(idequipo);
            ViewData["IDEQUIPO"] = equipo.IdEquipo;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(int idjugador,string nombre,string posicion,IFormFile imagen,int idequipo)
        {
            Jugador jugador = new Jugador();
            jugador.IdJugador = idjugador;
            jugador.Nombre = nombre;
            jugador.Posicion = posicion;
            jugador.Imagen = imagen.FileName;
            jugador.IdEquipo = idequipo;
            this.repo.CrearJugador(jugador);
            using (Stream stream = imagen.OpenReadStream())
            {
                await this.repo.UploadFile(stream, imagen.FileName);
            }
                
            return RedirectToAction("Index",new { idequipo=idequipo});
        }
    }
}

MvcExamenAWSAlvaroMoyaHerraiz/Views/Apuestas/Index.cshtml
@model IEnumerable<MvcExamenAWSAlvaroMoyaHerraiz.Models.Apuesta>

@{
    ViewData["Title"] = "Index";
    List<Equipo> equipos = ViewData["EQUIPOS"] as List<Equipo>;
}

<h1>Index</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GolesLocal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GolesVisitante)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GolesLocal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GolesVisitante)
            </td>
        </tr>
}
    </tbody>
</table>

<h2>Crea tu apuesta</h2>

<form method="post">
    <label>Usuario</label>
    <input name="usuario" type="text" class="form-control" />
    <br />
    <label>Equipo local</label>
    <select name="idlocal">
        @foreach (Equipo e in equipos)
        {
            <option value="@e.IdEquipo">@e.Nombre</option>
        }
    </select>
    <br />
    <label>Equipo Visitante</label>
    <select name="idvisitante">
        @foreach (Equipo e in equipos)
        {
            <option value="@e.IdEquipo">@e.Nombre</option>
        }
    </select>
    <br />
    <label>Goles Local</label>
    <input name="gollocal" type="number" class="form-control" />
    <br />
    <label>Goles Visitante</label>
    <input name="golvisitante" type="number" class="form-control" />
    <br />
    <input type="submit" value="Crear apuesta" class="btn btn-primary"/>
</form>

MvcExamenAWSAlvaroMoyaHerraiz/Views/Equipos/Index.cshtml
@model IEnumerable<MvcExamenAWSAlvaroMoyaHerraiz.Models.Equipo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Champions)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Web)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <img src="@item.Imagen" style="width:100px;height:100px;"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Champions)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Web)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                <a asp-action="Index" asp-controller="Jugadores" asp-route-idequipo="@item.IdEquipo" class="btn btn-info">Jugadores</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcExamenAWSAlvaroMoyaHerraiz/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcExamenAWSAlvaroMoyaHerraiz/Views/Jugadores/Create.cshtml
@model MvcExamenAWSAlvaroMoyaHerraiz.Models.Jugador

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Jugador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdJugador" class="control-label"></label>
                <input asp-for="IdJugador" class="form-control" />
                <span asp-validation-for="IdJugador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Posicion" class="control-label"></label>
                <input asp-for="Posicion" class="form-control" />
                <span asp-validation-for="Posicion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input asp-for="Imagen" type="file" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
                <input hidden value="@ViewData["IDEQUIPO"]" name="idequipo" class="form-control" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcExamenAWSAlvaroMoyaHerraiz/Views/Jugadores/Index.cshtml
@model IEnumerable<MvcExamenAWSAlvaroMoyaHerraiz.Models.Jugador>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<td>
    <a asp-action="Create" asp-route-idequipo="@ViewData["ID"]">Crear Jugador</a>
</td>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Posicion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdEquipo)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Posicion)
            </td>
            <td>
                <img style="height:100px;width:100px" src="https://bucket-examen-amh.s3.amazonaws.com/@item.Imagen">
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdEquipo)
            </td>
        </tr>
}
    </tbody>
</table>

MvcExamenAWSAlvaroMoyaHerraiz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcExamenAWSAlvaroMoyaHerraiz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcExamenAWSAlvaroMoyaHerraiz</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Equipos" asp-action="Index">Equipos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Apuestas" asp-action="Index">Apuestas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcExamenAWSAlvaroMoyaHerraiz - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>